### ISSUE TITLE
pedersen commitments inside EVM for scalability and privacy

### ISSUE THREAD

**Issue by barryWhiteHat** [ewasm/ewasm-precompiles#25]
## Motivation
So inside the snark its really expensive to use sha256 or other binary hash functions. So we want to use pedersen commitments where ever we can. But this means that the EVM and SNARK do not speak the same language. EVM can do sha256 hashes but snarks can do pedersen. 

## Status Quo
At the moment we end up doing a bunch of sha256 operations inside the snark which ends up being majority of the complexity inside the snark. We can do pedersen commitments insde the EVM but the gas costs are prohibative (~10000 gas)

It would be cool to have pre-compile for pedersen commitments for altbn128 and bls12-381 Precompile https://github.com/barryWhiteHat/baby_jubjub 

This would help a bunch with our with our scalability via snarks work as it would reduce the size of our snark circuits and let us add more signatures in their place :)

It would also help with our anonymity work as having to use sha256 in the snark circuit means that users must spend ~1 minute per proof and are just not able to do this on mobile. We can again use pedersen commitments in the snark but the EVM not supporing this opperation makes our smart contract need to become expensive. Or charge ppl 10,000 gas extra per deposit.

**Comment by barryWhiteHat** [comment]
Here is some python code for eddsa and pedersen commitments 

https://github.com/HarryR/ethsnarks/blob/master/ethsnarks/pedersen.py
https://github.com/HarryR/ethsnarks/blob/master/ethsnarks/eddsa.py

**Comment by cdetrio** [comment]
I believe this would be superseded by a precompile for general elliptic curve math (https://ethereum-magicians.org/t/ewasm-precompile-for-general-elliptic-curve-math/2581). right?

**Comment by barryWhiteHat** [comment]
Agree, closing
