### ISSUE TITLE
ecpairing behavior is different from that of geth on modulus size

### ISSUE THREAD

**Issue by gballet** [ewasm/ewasm-precompiles#45]
In [rinkeby block 2414440](https://rinkeby.etherscan.io/block/2414440) and using `geth`, a call to address 0x000...08 (ec pairing contract) with the following input:

```
44 28 190 130 151 54 30 125 7 14 242 247 229 30 78 206 30 253 164 240 174 49 229 149 80 132 239 97 45 117 32 223 23 11 215 225 180 61 188 131 57 225 212 22 44 43 183 188 84 36 119 223 203 57 181 48 198 77 0 66 247 72 31 109 25 142 147 147 146 13 72 58 114 96 191 183 49 251 93 37 241 170 73 51 53 169 231 18 151 228 133 183 174 243 18 194 24 0 222 239 18 31 30 118 66 106 0 102 94 92 68 121 103 67 34 212 247 94 218 221 70 222 189 92 217 146 246 237 9 6 137 208 88 95 240 117 236 158 153 173 105 12 51 149 188 75 49 51 112 179 142 243 85 172 218 220 209 34 151 91 18 200 94 165 219 140 109 235 74 171 113 128 141 203 64 143 227 209 231 105 12 67 211 123 76 230 204 1 102 250 125 170 17 253 60 56 234 9 125 220 77 186 211 128 137 220 33 185 229 126 251 164 93 244 13 67 103 192 250 223 103 84 203 214 25 165 245 192 255 0 170 177 47 147 244 250 250 233 55 58 42 86 203 166 115 13 40 106 80 199 74 218 176 15 4 221 41 115 9 30 125 148 169 185 161 153 123 103 129 111 235 232 147 122 3 243 19 111 6 233 191 38 118 252 236 248 0 77 155 229 221 156 32 174 100 137 181 7 135 92 199 111 103 249 161 171 170 15 214 224 153 121 148 41 42 213 73 194 146 96 21 81 155 4 0 125 78 52 32 148 8 133 126 111 206 254 34 88 115 250 110 50 214 175 52 13 219 86 21 172 244 71 16 80 100 76 82 173 75 210 2 55 167 165 162 47 111 48 50 21 191 106 155 204 249 55 158 23 193 225 222 242 218 7
```

will cause the following error: `bn256: coordinate exceeds modulus`. It also performs a `revert`.

The current version of the ewasm precompile ignore the answer and return no error along with `false` (which is an empty byte array) and the contract terminates normally. I need to investigate, which I will do tomorrow, however I'm creating an issue here in case someone has a quick answer to this issue.

**Comment by gballet** [comment]
correction, `revert` is indeed called in both cases.

**Comment by axic** [comment]
So is it buggy or not?

**Comment by gballet** [comment]
it is not buggy, it is a difference of behavior: one of them returns an error upon `revert`-ing and the other one doesn't.

**Comment by axic** [comment]
What do you mean returns an error upon revert? Revert returns a buffer? Is the message just displayed somewhere?

**Comment by gballet** [comment]
it's returned by the precompile function, then captured somewhere up the stack and interpreted as a request to consume all gas. That yield some pretty big difference, and that's the most common consensus difference between wasm and native on rinkeby. I'm studying several options to handle this the best way possible.

**Comment by axic** [comment]
Ah!

I think the problem is we are doing revert in our precompiles for some reason, but precompiles actually do OOG. We should add `ewasm_api::abort` to https://github.com/ewasm/ewasm-rust-api (cc @jakelang), but for the moment you can use `panic!()`.

The rust-api stuff could use the underlying wasm opcode `unreachable` in the future.

**Comment by gballet** [comment]
`panic!()` solved the issue, I'll give `abort` a try as well but it doesn't seem to be necessary.
